import Mathlib.FieldTheory.Galois.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
## Chebotarev reduction: fixed field of a cyclic subgroup

Sharifi’s reduction step (Thm 7.2.2, Step 1) passes from a conjugacy class `C ⊆ Gal(L/K)` to the
intermediate field `E = L^{⟨σ⟩}` fixed by the cyclic subgroup generated by `σ ∈ C`.  The extension
`L/E` then has cyclic Galois group.

This file packages the corresponding **purely algebraic** facts using mathlib’s Galois
correspondence (`IntermediateField.fixedField` / `IntermediateField.subgroupEquivAlgEquiv`).

No analytic input appears here.
-/

namespace PrimeNumberTheoremAnd

namespace Chebotarev

open scoped Classical

section

variable (K L : Type*) [Field K] [Field L] [Algebra K L]

variable (σ : Gal(L/K))

/-- The intermediate field fixed by the cyclic subgroup generated by `σ`. -/
def fixedFieldZpowers : IntermediateField K L :=
  IntermediateField.fixedField (Subgroup.zpowers σ)

@[simp] lemma fixedFieldZpowers_def :
    fixedFieldZpowers (K := K) (L := L) σ = IntermediateField.fixedField (Subgroup.zpowers σ) := rfl

variable [FiniteDimensional K L]

/--
The Galois group of `L` over the fixed field of `⟨σ⟩` is cyclic.

This is immediate from the canonical isomorphism
`Subgroup.zpowers σ ≃* Gal(L / fixedField (Subgroup.zpowers σ))`.
-/
theorem isCyclic_gal_fixedFieldZpowers :
    IsCyclic (Gal(L/fixedFieldZpowers (K := K) (L := L) σ)) := by
  classical
  -- Galois correspondence: subgroup ↔ automorphisms over its fixed field.
  let e :
      (Subgroup.zpowers σ) ≃*
        Gal(L / IntermediateField.fixedField (Subgroup.zpowers σ)) :=
    IntermediateField.subgroupEquivAlgEquiv (F := K) (E := L) (H := Subgroup.zpowers σ)
  -- Transfer cyclicity across the group equivalence.
  have hcyc : IsCyclic (Subgroup.zpowers σ) := by infer_instance
  -- rewrite the target to match `e`
  simpa [fixedFieldZpowers, e] using (MulEquiv.isCyclic e).1 hcyc

/-!
As a convenient corollary: `Gal(L/L^{⟨σ⟩})` is commutative.

We keep this as a lemma (not a global instance) to avoid unexpected instance search effects.
-/
theorem mul_comm_gal_fixedFieldZpowers (a b : Gal(L/fixedFieldZpowers (K := K) (L := L) σ)) :
    a * b = b * a := by
  classical
  haveI : IsCyclic (Gal(L/fixedFieldZpowers (K := K) (L := L) σ)) :=
    isCyclic_gal_fixedFieldZpowers (K := K) (L := L) σ
  simpa using
    (IsCyclic.commutative (α := Gal(L/fixedFieldZpowers (K := K) (L := L) σ))).comm a b

end

end Chebotarev

end PrimeNumberTheoremAnd

